### ISSUE TITLE
No such signal when relaunching

### ISSUE THREAD

**Issue by skarekrow** [trueos/diligent#2]
The error message is:
```
QObject::connect: No such signal WebPage::urlChanged(QUrl)
QObject::connect: No such signal WebPage::urlChanged(QUrl)
```
That is with 2 tabs open. To reproduce:

1. Launch Diligent and connect to a team
2. Close Diligent
3. Open Diligent again

You'll see those spit out in the console.

Qt is version 5.7.0 on Arch Linux.

**Comment by beanpole135** [comment]
Fixed!!

https://github.com/trueos/diligent/commit/19aef1bcd7c5b85d91d9a71bd252d24d0c541bf7

**Comment by skarekrow** [comment]
\m/
