### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by q5sys** [trueos/diligent#3]
make: "/usr/home/q5sys/git/diligent/diligent/Makefile" line 2074: warning: duplicate script for target "moc_mainapplication.cpp" ignored
make: "/usr/home/q5sys/git/diligent/diligent/Makefile" line 980: warning: using previous script for "moc_mainapplication.cpp" defined here

**Comment by beanpole135** [comment]
Try running "make clean" first

**Comment by beanpole135** [comment]
or "make distclean" and qmake && make again

**Comment by q5sys** [comment]
That's from a fresh git pull.  I did make clean and make distclean and then did qmake $$ make and the error still persists.  The .pro file doesnt seem to have anything wrong, not sure why the makefile is acting the way it is.

**Comment by q5sys** [comment]
It will continue to compile and the binary will run if started manually from that directory, but 'sudo make install' will fail with the same error and not properly install the binary and additional files to the correct locations.

**Comment by kmoore134** [comment]
This issue was moved to trueos/trueos-core#70
